/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ub.hrappub.service.ui;

import com.ub.hrappub.entity.EBirim;
import com.ub.hrappub.entity.EUnvan;
import com.ub.hrappub.entity.Personel;
import com.ub.hrappub.service.PersonelService;
import com.ub.hrappub.util.DefaultComboModel;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Ugur
 */
public class frmPersonelEkle extends javax.swing.JFrame {

    byte[] fotoDosya;
    String fotoAdres;
    
    
    /**
     * Creates new form frmPersonelEkle
     */
    public frmPersonelEkle() {
        initComponents();
        setLocationRelativeTo(null);
        comboUnvan();
        comboBirim();
        
    }

    public frmPersonelEkle(Personel personel) {
        initComponents();
        setLocationRelativeTo(null);
        
        txtAdSoyad.setText(personel.getAdSoyad());
        
        JComboBox<EUnvan> cmbUnvan = new JComboBox();
        cmbUnvan.setModel(new DefaultComboBoxModel(personel.getUnvan().values()));
        
        JComboBox<EBirim> cmbBirim = new JComboBox();
        cmbBirim.setModel(new DefaultComboBoxModel(personel.getBirimi().values()));
                
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAdSoyad = new javax.swing.JLabel();
        txtAdSoyad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSicilNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnIptal = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        cmbUnvan = new javax.swing.JComboBox<>();
        cmbBirim = new javax.swing.JComboBox<>();
        txtGirisTarihi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdSoyad.setText("İsim:");

        jLabel1.setText("Ünvan:");

        jLabel2.setText("Birim:");

        jLabel3.setText("Sicil No:");

        jLabel4.setText("Giriş Tarihi:");

        btnIptal.setText("İptal");
        btnIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIptalActionPerformed(evt);
            }
        });

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        cmbUnvan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBirim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAdSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdSoyad)
                            .addComponent(txtSicilNo)
                            .addComponent(cmbBirim, 0, 90, Short.MAX_VALUE)
                            .addComponent(cmbUnvan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGirisTarihi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIptal)
                        .addGap(40, 40, 40)
                        .addComponent(btnGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdSoyad)
                    .addComponent(txtAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUnvan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbBirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSicilNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtGirisTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIptal)
                    .addComponent(btnGiris))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        int secim = JOptionPane.showConfirmDialog(rootPane, "Çıkmak istediğinizden emin misiniz? Kaydedilmemiş veriler kaybedilecek!!!", "Çıkış", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (secim == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnIptalActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        
        try {
            PersonelService personelService = new PersonelService();
            Personel yeniPersonel = new Personel();
            
            yeniPersonel.setAdSoyad(txtAdSoyad.getText());
            
            DefaultComboModel secilenUnvan = (DefaultComboModel) cmbUnvan.getSelectedItem();
            EUnvan unvan = EUnvan.getEnum(secilenUnvan.getValue().intValue());
            yeniPersonel.setUnvan(unvan);
            
            DefaultComboModel secilenBirim = (DefaultComboModel) cmbBirim.getSelectedItem();
            EBirim birim = EBirim.getEnum(secilenBirim.getValue().intValue());
            yeniPersonel.setBirimi(birim);
            
            yeniPersonel.setSicilNo(new Long(txtSicilNo.getText()));
            yeniPersonel.setGirisTarihi(new Date(txtGirisTarihi.getText()));
            
            if (txtSicilNo.getText().equals("")) {
                personelService.save(yeniPersonel);
                this.dispose();
            } else {
                yeniPersonel.setSicilNo(new Long(txtSicilNo.getText()));
                personelService.update(yeniPersonel);
                this.dispose();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    
    }//GEN-LAST:event_btnGirisActionPerformed

    
    private void comboUnvan(){
        
        DefaultComboModel[] dizi = new DefaultComboModel[4];
        for (int i = 0; i < EUnvan.values().length; i++) {
            String label = EUnvan.values()[i].getLabel();
            dizi[i] = new DefaultComboModel(new Long(i), label);
        }
        cmbUnvan.setModel(new DefaultComboBoxModel(dizi));
        
    }
    
    private void comboBirim(){
        
        DefaultComboModel[] dizi = new DefaultComboModel[2];
        for (int i = 0; i < EBirim.values().length; i++) {
            String label = EBirim.values()[i].getLabel();
            dizi[i] = new DefaultComboModel(new Long(i), label);
        }
        cmbBirim.setModel(new DefaultComboBoxModel(dizi));
        
    }
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnIptal;
    private javax.swing.JComboBox<String> cmbBirim;
    private javax.swing.JComboBox<String> cmbUnvan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdSoyad;
    private javax.swing.JTextField txtAdSoyad;
    private javax.swing.JTextField txtGirisTarihi;
    private javax.swing.JTextField txtSicilNo;
    // End of variables declaration//GEN-END:variables
}
